feat: add check for Git repository in autocommit function
This update enhances the autocommit function by introducing a condition that confirms whether the current directory is part of a Git repository before attempting an autocommit.

This enhancement prevents processing of the autocmmit function in directories that are not Git repositories and presents an error message to the user, improving overall user experience and preventing potential confusions or errors.

diff --git a/zsh/.zsh/zsh_alias b/zsh/.zsh/zsh_alias
--- a/zsh/.zsh/zsh_alias
+++ b/zsh/.zsh/zsh_alias
@@ -1,4 +1,9 @@
 function autocommit() {
+    if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
+        echo "Error: Not a Git repository"
+        return 1
+    fi
+
     echo "Let's AutoCommit"
     local commit_file="/tmp/commit.txt"
     # trap 'rm -f "$commit_file"' EXIT
